In [ ]:
import pandas as pd
import numpy as np

sales = pd.read_csv("../data/raw/sales.csv")
web_traffic = pd.read_csv("../data/raw/web_traffic.csv")
products = pd.read_csv("../data/raw/products.csv")
orders = pd.read_csv("../data/raw/orders.csv")
promotions = pd.read_csv("../data/raw/promotions.csv")

np.random.seed(0)

In [8]:
def percent_missing(file_name):
    total = np.prod(file_name.shape)
    missing = file_name.isnull().sum()
    total_missing = missing.sum()
    per_missing = (total_missing/total) * 100
    return per_missing

In [9]:
print(f"Percent Missing sales: {percent_missing(sales)}")
print(f"Percent Missing web_traffic: {percent_missing(web_traffic)}")
print(f"Percent Missing products: {percent_missing(products)}")
print(f"Percent Missing orders: {percent_missing(orders)}")
print(f"Percent Missing promotions: {percent_missing(promotions)}")

Percent Missing sales: 0.0
Percent Missing web_traffic: 0.0
Percent Missing products: 0.0
Percent Missing orders: 0.0
Percent Missing promotions: 8.0

In [10]:
promotions.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,NaN,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,NaN,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,NaN,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,NaN,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [11]:
promotions['applicable_category'] = promotions['applicable_category'].fillna('All')

In [12]:
promotions.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,All,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,All,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,All,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,All,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [13]:
print(f"Percent Missing promotions: {percent_missing(promotions)}")

Percent Missing promotions: 0.0

In [14]:
print(f"Date type sales: {sales['Date'].dtype}")
print(f"Date type web_traffic: {web_traffic['date'].dtype}")
print(f"Date type orders: {orders['order_date'].dtype}")
print(f"Date type promotions: {promotions['start_date'].dtype}, {promotions['end_date'].dtype}")

Date type sales: object
Date type web_traffic: object
Date type orders: object
Date type promotions: object, object

In [15]:
sales['Date'] = pd.to_datetime(sales['Date'], format="%Y-%m-%d")
web_traffic['date'] = pd.to_datetime(web_traffic['date'], format="%Y-%m-%d")
orders['order_date'] = pd.to_datetime(orders['order_date'], format="%Y-%m-%d")
promotions['start_date'] = pd.to_datetime(promotions['start_date'], format="%Y-%m-%d")
promotions['end_date'] = pd.to_datetime(promotions['end_date'], format="%Y-%m-%d")

In [16]:
print(f"Date type sales: {sales['Date'].dtype}")
print(f"Date type web_traffic: {web_traffic['date'].dtype}")
print(f"Date type orders: {orders['order_date'].dtype}")
print(f"Date type promotions: {promotions['start_date'].dtype}, {promotions['end_date'].dtype}")

Date type sales: datetime64[ns]
Date type web_traffic: datetime64[ns]
Date type orders: datetime64[ns]
Date type promotions: datetime64[ns], datetime64[ns]